In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
import pandas as pd
file_path = "/Users/Aryaanil/Documents/loan prediction.csv.xls"
df = pd.read_csv(file_path)
print(df)

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN           

In [3]:
print(df.isnull().sum())

cat_cols = ['Gender', 'Married', 'Dependents',
            'Self_Employed', 'Loan_Amount_Term',
            'Credit_History']

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64


/var/folders/2q/c34xq8nn70lgm5zqqcds5x7m0000gn/T/ipykernel_48462/1739711556.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/var/folders/2q/c34xq8nn70lgm5zqqcds5x7m0000gn/T/ipykernel_48462/1739711556.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values alwa

In [4]:
df['TotalIncome'] = df['ApplicantIncome'] + df['CoapplicantIncome']

# Drop Loan_ID
df.drop('Loan_ID', axis=1, inplace=True)


In [5]:
le = LabelEncoder()

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])


In [6]:
X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']


In [7]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (491, 12)
X_test shape: (123, 12)


In [9]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier()
}

results = {}


In [10]:
for name, model in models.items():

    model.fit(X_train, y_train)


    y_pred = model.predict(X_test)

 
    accuracy = accuracy_score(y_test, y_pred)

    results[name] = accuracy

    print("\n============================")
    print(name)
    print("============================")

    print("Accuracy:", accuracy)

    print("\nConfusion Matrix")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report")
    print(classification_report(y_test, y_pred))


Logistic Regression
Accuracy: 0.7886178861788617

Confusion Matrix
[[18 25]
 [ 1 79]]

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.42      0.58        43
           1       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123


Decision Tree
Accuracy: 0.7154471544715447

Confusion Matrix
[[23 20]
 [15 65]]

Classification Report
              precision    recall  f1-score   support

           0       0.61      0.53      0.57        43
           1       0.76      0.81      0.79        80

    accuracy                           0.72       123
   macro avg       0.68      0.67      0.68       123
weighted avg       0.71      0.72      0.71       123


Random Forest
Accuracy: 0.7642276422764228

Confusion Matrix
[[19 24]
 [ 5 75]]

Classification Report
              precision    r

In [11]:
print("\n=========== MODEL COMPARISON ===========")

for model, score in results.items():
    print(model, ":", score)



=========== MODEL COMPARISON ===========
Logistic Regression : 0.7886178861788617
Decision Tree : 0.7154471544715447
Random Forest : 0.7642276422764228
KNN : 0.7560975609756098


In [12]:
best_model = max(results, key=results.get)

print("\nBest Model is:", best_model)
print("Best Accuracy:", results[best_model])



Best Model is: Logistic Regression
Best Accuracy: 0.7886178861788617


In [13]:
print("\nFINAL REPORT")
print("1. Data Cleaning Completed")
print("2. Feature Engineering Completed")
print("3. Encoding Completed")
print("4. Scaling Completed")
print("5. Train-Test Split Completed")
print("6. Multiple Models Trained")
print("7. Models Compared Successfully")
print("8. Best Model Selected")


FINAL REPORT
1. Data Cleaning Completed
2. Feature Engineering Completed
3. Encoding Completed
4. Scaling Completed
5. Train-Test Split Completed
6. Multiple Models Trained
7. Models Compared Successfully
8. Best Model Selected
